"""empty message

Revision ID: 333440cacf71
Revises: 7d5996650e44
Create Date: 2025-09-22 10:49:10.726149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '333440cacf71'
down_revision = '7d5996650e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_table('case__template__connector__instance',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('case_template_id', sa.Integer(), nullable=True),
        sa.Column('connector_instance_id', sa.Integer(), nullable=True),
        sa.Column('identifier', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    except OperationalError:
        print("Table 'case__template__connector__instance' already exist")
          
    try:
        with op.batch_alter_table('case__template__connector__instance', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_case__template__connector__instance_case_template_id'), ['case_template_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_case__template__connector__instance_connector_instance_id'), ['connector_instance_id'], unique=False)
    except OperationalError:
        print("Indexes already exist ")

    try:
        with op.batch_alter_table('connector__instance', schema=None) as batch_op:
            batch_op.add_column(sa.Column('global_api_key', sa.String(length=100), nullable=True))
            batch_op.create_index(batch_op.f('ix_connector__instance_global_api_key'), ['global_api_key'], unique=False)
    except OperationalError:
        print("Column 'global_api_key' already exist in 'connector__instance'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('connector__instance', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_connector__instance_global_api_key'))
            batch_op.drop_column('global_api_key')
    except OperationalError:
        print("Column 'global_api_key' already dropped from 'connector__instance'")

    try:
        with op.batch_alter_table('case__template__connector__instance', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_case__template__connector__instance_connector_instance_id'))
            batch_op.drop_index(batch_op.f('ix_case__template__connector__instance_case_template_id'))
    except OperationalError:
        print("Indexes already dropped")

    try:
        op.drop_table('case__template__connector__instance')
    except OperationalError:
        print("Table 'case__template__connector__instance' already dropped")
    # ### end Alembic commands ###
